### PR TITLE
Solution [Danylo Kunchenko]

### PR DESCRIPTION
**Pull request by d-kunchenko**

### CODE REVIEW

**Comment by Alex-edge-Johnson** [comment]
Good job!
Consider removing empty lines after every action, there is no need for this. Empty lines are usually used in tests to separate some code blocks, e.g. for preparing test data, performing an action, and asserting the result.

**Comment by Andreii12** [comment]
gj

**Review by nkondd — COMMENTED** [review]
GJ!

**Comment by maxymbeshleha** [comment]
GJ

**Review by maxymbeshleha — COMMENTED** [review]
GJ

**Comment by OleksandraZen** [comment]
Good Job!:)

**Review by MykolaFedasiuk — APPROVED** [review]

**Review by Andreii12 — APPROVED** [review]

**Review by tnboyko — APPROVED** [review]

**Review by Alex-edge-Johnson — APPROVED** [review]

**Pull request closed without merging**
